language: python
python:
  - 3.7.5

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "Travis is running!"

script:
  - docker --version # print the version for logging
  - docker build -t fma_image .
  - docker tag fma_image srivathsan930v/fma_image:latest

after_success:
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
  - docker push srivathsan930v/fma_image